{
 "title": "Node Exporter Metrics",
 "description": "Dashboard to view multiple servers",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\"}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{} - node_memory_SwapCached_bytes{} - node_memory_Slab_bytes{} - node_memory_PageTables_bytes{} - node_memory_VmallocUsed_bytes{} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab{instance=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached{instance=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables{instance=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed{instance=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive{instance=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1{}", "legendFormat": "load" }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_time_seconds_total{instance=~'$node'}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab{}", "legendFormat": "established" }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{} - node_nf_conntrack_entries{}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}