# datasources.yaml
apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      dbName: $DOCKER_INFLUXDB_INIT_BUCKET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN'
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy